# Generated by Django 3.2.4 on 2021-07-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=52)),
                ('last_name', models.CharField(max_length=52)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=52)),
                ('password', models.CharField(max_length=502)),
            ],
        ),
    ]
